name: Release prerelease APK

on:
  workflow_dispatch:
    branches:
      - dev

concurrency:
  group: release-prerelease-dev
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build-apk-shared.yml
    permissions:
      contents: write
    with:
      publish_prerelease: true
